#!/bin/bash

# Lib

print_title() {
  tput bold
  echo -n "$1: "
  tput sgr0
}


print_success() {
  tput setaf 2
  echo 'OK'
  tput sgr0
}


print_error() {
  tput setaf 1
  echo 'ERR'
  tput sgr0
}


run_step() {
  print_title "$1"

  if output="$(bash -c "$2" 2>&1)"; then
    print_success
    return 0
  fi

  print_error
  echo "$output" | sed -r 's/(.*)/  \1/'
  return 1
}


find_conf() {
  path="$(realpath "$1")"
  conf="$path/.commit-rules"

  if [ -e "$conf" ]; then
    echo "$conf"
    return 0
  fi

  if [ "$path" == "/" ]; then
    return 1
  fi

  find_conf "$path/.."
}


read_conf() {
  sed -rn '/^#/d; s/^([0-9A-Za-z -_.,/]+):\s*(.+)/\1\t\2/p' "$1"
}


run() {
  if ! conf="$(find_conf .)"; then
    echo "Arquivo de configuração não encontrado!"
    return 1
  fi

  while IFS="$(echo -ne "\t")" read name prog; do
    if ! run_step "$name" "$prog"; then
      return 1
    fi
  done < <(read_conf "$conf")
  return 0
}


# Run

run
